// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Struct.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Protocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocol_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Protocol_2eproto;
namespace Protocol {
class CS_FIELD_LOADING_COMPLETE;
struct CS_FIELD_LOADING_COMPLETEDefaultTypeInternal;
extern CS_FIELD_LOADING_COMPLETEDefaultTypeInternal _CS_FIELD_LOADING_COMPLETE_default_instance_;
class CS_REQUEST_MOVE;
struct CS_REQUEST_MOVEDefaultTypeInternal;
extern CS_REQUEST_MOVEDefaultTypeInternal _CS_REQUEST_MOVE_default_instance_;
class CS_REQ_ENTER_GAME;
struct CS_REQ_ENTER_GAMEDefaultTypeInternal;
extern CS_REQ_ENTER_GAMEDefaultTypeInternal _CS_REQ_ENTER_GAME_default_instance_;
class CS_REQ_MOVE_FIELD;
struct CS_REQ_MOVE_FIELDDefaultTypeInternal;
extern CS_REQ_MOVE_FIELDDefaultTypeInternal _CS_REQ_MOVE_FIELD_default_instance_;
class CS_TIME_SYNC;
struct CS_TIME_SYNCDefaultTypeInternal;
extern CS_TIME_SYNCDefaultTypeInternal _CS_TIME_SYNC_default_instance_;
class SC_DESPAWN_PLAYER;
struct SC_DESPAWN_PLAYERDefaultTypeInternal;
extern SC_DESPAWN_PLAYERDefaultTypeInternal _SC_DESPAWN_PLAYER_default_instance_;
class SC_ENTER_FIELD;
struct SC_ENTER_FIELDDefaultTypeInternal;
extern SC_ENTER_FIELDDefaultTypeInternal _SC_ENTER_FIELD_default_instance_;
class SC_ENTER_GAME_RESULT;
struct SC_ENTER_GAME_RESULTDefaultTypeInternal;
extern SC_ENTER_GAME_RESULTDefaultTypeInternal _SC_ENTER_GAME_RESULT_default_instance_;
class SC_MOVE_FIELD_FAIL;
struct SC_MOVE_FIELD_FAILDefaultTypeInternal;
extern SC_MOVE_FIELD_FAILDefaultTypeInternal _SC_MOVE_FIELD_FAIL_default_instance_;
class SC_MOVE_PATH;
struct SC_MOVE_PATHDefaultTypeInternal;
extern SC_MOVE_PATHDefaultTypeInternal _SC_MOVE_PATH_default_instance_;
class SC_SPAWN_PLAYER;
struct SC_SPAWN_PLAYERDefaultTypeInternal;
extern SC_SPAWN_PLAYERDefaultTypeInternal _SC_SPAWN_PLAYER_default_instance_;
class SC_START_FIELD_LOADING;
struct SC_START_FIELD_LOADINGDefaultTypeInternal;
extern SC_START_FIELD_LOADINGDefaultTypeInternal _SC_START_FIELD_LOADING_default_instance_;
class SC_TIME_SYNC;
struct SC_TIME_SYNCDefaultTypeInternal;
extern SC_TIME_SYNCDefaultTypeInternal _SC_TIME_SYNC_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::CS_FIELD_LOADING_COMPLETE* Arena::CreateMaybeMessage<::Protocol::CS_FIELD_LOADING_COMPLETE>(Arena*);
template<> ::Protocol::CS_REQUEST_MOVE* Arena::CreateMaybeMessage<::Protocol::CS_REQUEST_MOVE>(Arena*);
template<> ::Protocol::CS_REQ_ENTER_GAME* Arena::CreateMaybeMessage<::Protocol::CS_REQ_ENTER_GAME>(Arena*);
template<> ::Protocol::CS_REQ_MOVE_FIELD* Arena::CreateMaybeMessage<::Protocol::CS_REQ_MOVE_FIELD>(Arena*);
template<> ::Protocol::CS_TIME_SYNC* Arena::CreateMaybeMessage<::Protocol::CS_TIME_SYNC>(Arena*);
template<> ::Protocol::SC_DESPAWN_PLAYER* Arena::CreateMaybeMessage<::Protocol::SC_DESPAWN_PLAYER>(Arena*);
template<> ::Protocol::SC_ENTER_FIELD* Arena::CreateMaybeMessage<::Protocol::SC_ENTER_FIELD>(Arena*);
template<> ::Protocol::SC_ENTER_GAME_RESULT* Arena::CreateMaybeMessage<::Protocol::SC_ENTER_GAME_RESULT>(Arena*);
template<> ::Protocol::SC_MOVE_FIELD_FAIL* Arena::CreateMaybeMessage<::Protocol::SC_MOVE_FIELD_FAIL>(Arena*);
template<> ::Protocol::SC_MOVE_PATH* Arena::CreateMaybeMessage<::Protocol::SC_MOVE_PATH>(Arena*);
template<> ::Protocol::SC_SPAWN_PLAYER* Arena::CreateMaybeMessage<::Protocol::SC_SPAWN_PLAYER>(Arena*);
template<> ::Protocol::SC_START_FIELD_LOADING* Arena::CreateMaybeMessage<::Protocol::SC_START_FIELD_LOADING>(Arena*);
template<> ::Protocol::SC_TIME_SYNC* Arena::CreateMaybeMessage<::Protocol::SC_TIME_SYNC>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class CS_REQ_ENTER_GAME final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.CS_REQ_ENTER_GAME) */ {
 public:
  inline CS_REQ_ENTER_GAME() : CS_REQ_ENTER_GAME(nullptr) {}
  ~CS_REQ_ENTER_GAME() override;
  explicit PROTOBUF_CONSTEXPR CS_REQ_ENTER_GAME(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CS_REQ_ENTER_GAME(const CS_REQ_ENTER_GAME& from);
  CS_REQ_ENTER_GAME(CS_REQ_ENTER_GAME&& from) noexcept
    : CS_REQ_ENTER_GAME() {
    *this = ::std::move(from);
  }

  inline CS_REQ_ENTER_GAME& operator=(const CS_REQ_ENTER_GAME& from) {
    CopyFrom(from);
    return *this;
  }
  inline CS_REQ_ENTER_GAME& operator=(CS_REQ_ENTER_GAME&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CS_REQ_ENTER_GAME& default_instance() {
    return *internal_default_instance();
  }
  static inline const CS_REQ_ENTER_GAME* internal_default_instance() {
    return reinterpret_cast<const CS_REQ_ENTER_GAME*>(
               &_CS_REQ_ENTER_GAME_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CS_REQ_ENTER_GAME& a, CS_REQ_ENTER_GAME& b) {
    a.Swap(&b);
  }
  inline void Swap(CS_REQ_ENTER_GAME* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CS_REQ_ENTER_GAME* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CS_REQ_ENTER_GAME* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CS_REQ_ENTER_GAME>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CS_REQ_ENTER_GAME& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CS_REQ_ENTER_GAME& from) {
    CS_REQ_ENTER_GAME::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CS_REQ_ENTER_GAME* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.CS_REQ_ENTER_GAME";
  }
  protected:
  explicit CS_REQ_ENTER_GAME(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCharIdFieldNumber = 1,
    kTokenFieldNumber = 2,
  };
  // int32 char_id = 1;
  void clear_char_id();
  int32_t char_id() const;
  void set_char_id(int32_t value);
  private:
  int32_t _internal_char_id() const;
  void _internal_set_char_id(int32_t value);
  public:

  // int32 token = 2;
  void clear_token();
  int32_t token() const;
  void set_token(int32_t value);
  private:
  int32_t _internal_token() const;
  void _internal_set_token(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.CS_REQ_ENTER_GAME)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t char_id_;
    int32_t token_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class SC_ENTER_GAME_RESULT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.SC_ENTER_GAME_RESULT) */ {
 public:
  inline SC_ENTER_GAME_RESULT() : SC_ENTER_GAME_RESULT(nullptr) {}
  ~SC_ENTER_GAME_RESULT() override;
  explicit PROTOBUF_CONSTEXPR SC_ENTER_GAME_RESULT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SC_ENTER_GAME_RESULT(const SC_ENTER_GAME_RESULT& from);
  SC_ENTER_GAME_RESULT(SC_ENTER_GAME_RESULT&& from) noexcept
    : SC_ENTER_GAME_RESULT() {
    *this = ::std::move(from);
  }

  inline SC_ENTER_GAME_RESULT& operator=(const SC_ENTER_GAME_RESULT& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_ENTER_GAME_RESULT& operator=(SC_ENTER_GAME_RESULT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_ENTER_GAME_RESULT& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_ENTER_GAME_RESULT* internal_default_instance() {
    return reinterpret_cast<const SC_ENTER_GAME_RESULT*>(
               &_SC_ENTER_GAME_RESULT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SC_ENTER_GAME_RESULT& a, SC_ENTER_GAME_RESULT& b) {
    a.Swap(&b);
  }
  inline void Swap(SC_ENTER_GAME_RESULT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_ENTER_GAME_RESULT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_ENTER_GAME_RESULT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SC_ENTER_GAME_RESULT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SC_ENTER_GAME_RESULT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SC_ENTER_GAME_RESULT& from) {
    SC_ENTER_GAME_RESULT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SC_ENTER_GAME_RESULT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.SC_ENTER_GAME_RESULT";
  }
  protected:
  explicit SC_ENTER_GAME_RESULT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
    kErrorCodeFieldNumber = 2,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // int32 error_code = 2;
  void clear_error_code();
  int32_t error_code() const;
  void set_error_code(int32_t value);
  private:
  int32_t _internal_error_code() const;
  void _internal_set_error_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.SC_ENTER_GAME_RESULT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool success_;
    int32_t error_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class CS_REQ_MOVE_FIELD final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.CS_REQ_MOVE_FIELD) */ {
 public:
  inline CS_REQ_MOVE_FIELD() : CS_REQ_MOVE_FIELD(nullptr) {}
  ~CS_REQ_MOVE_FIELD() override;
  explicit PROTOBUF_CONSTEXPR CS_REQ_MOVE_FIELD(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CS_REQ_MOVE_FIELD(const CS_REQ_MOVE_FIELD& from);
  CS_REQ_MOVE_FIELD(CS_REQ_MOVE_FIELD&& from) noexcept
    : CS_REQ_MOVE_FIELD() {
    *this = ::std::move(from);
  }

  inline CS_REQ_MOVE_FIELD& operator=(const CS_REQ_MOVE_FIELD& from) {
    CopyFrom(from);
    return *this;
  }
  inline CS_REQ_MOVE_FIELD& operator=(CS_REQ_MOVE_FIELD&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CS_REQ_MOVE_FIELD& default_instance() {
    return *internal_default_instance();
  }
  static inline const CS_REQ_MOVE_FIELD* internal_default_instance() {
    return reinterpret_cast<const CS_REQ_MOVE_FIELD*>(
               &_CS_REQ_MOVE_FIELD_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CS_REQ_MOVE_FIELD& a, CS_REQ_MOVE_FIELD& b) {
    a.Swap(&b);
  }
  inline void Swap(CS_REQ_MOVE_FIELD* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CS_REQ_MOVE_FIELD* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CS_REQ_MOVE_FIELD* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CS_REQ_MOVE_FIELD>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CS_REQ_MOVE_FIELD& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CS_REQ_MOVE_FIELD& from) {
    CS_REQ_MOVE_FIELD::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CS_REQ_MOVE_FIELD* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.CS_REQ_MOVE_FIELD";
  }
  protected:
  explicit CS_REQ_MOVE_FIELD(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMapIdFieldNumber = 1,
  };
  // uint32 map_id = 1;
  void clear_map_id();
  uint32_t map_id() const;
  void set_map_id(uint32_t value);
  private:
  uint32_t _internal_map_id() const;
  void _internal_set_map_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.CS_REQ_MOVE_FIELD)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t map_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class SC_MOVE_FIELD_FAIL final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.SC_MOVE_FIELD_FAIL) */ {
 public:
  inline SC_MOVE_FIELD_FAIL() : SC_MOVE_FIELD_FAIL(nullptr) {}
  ~SC_MOVE_FIELD_FAIL() override;
  explicit PROTOBUF_CONSTEXPR SC_MOVE_FIELD_FAIL(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SC_MOVE_FIELD_FAIL(const SC_MOVE_FIELD_FAIL& from);
  SC_MOVE_FIELD_FAIL(SC_MOVE_FIELD_FAIL&& from) noexcept
    : SC_MOVE_FIELD_FAIL() {
    *this = ::std::move(from);
  }

  inline SC_MOVE_FIELD_FAIL& operator=(const SC_MOVE_FIELD_FAIL& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_MOVE_FIELD_FAIL& operator=(SC_MOVE_FIELD_FAIL&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_MOVE_FIELD_FAIL& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_MOVE_FIELD_FAIL* internal_default_instance() {
    return reinterpret_cast<const SC_MOVE_FIELD_FAIL*>(
               &_SC_MOVE_FIELD_FAIL_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(SC_MOVE_FIELD_FAIL& a, SC_MOVE_FIELD_FAIL& b) {
    a.Swap(&b);
  }
  inline void Swap(SC_MOVE_FIELD_FAIL* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_MOVE_FIELD_FAIL* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_MOVE_FIELD_FAIL* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SC_MOVE_FIELD_FAIL>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SC_MOVE_FIELD_FAIL& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SC_MOVE_FIELD_FAIL& from) {
    SC_MOVE_FIELD_FAIL::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SC_MOVE_FIELD_FAIL* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.SC_MOVE_FIELD_FAIL";
  }
  protected:
  explicit SC_MOVE_FIELD_FAIL(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorCodeFieldNumber = 1,
  };
  // int32 error_code = 1;
  void clear_error_code();
  int32_t error_code() const;
  void set_error_code(int32_t value);
  private:
  int32_t _internal_error_code() const;
  void _internal_set_error_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.SC_MOVE_FIELD_FAIL)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t error_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class SC_START_FIELD_LOADING final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.SC_START_FIELD_LOADING) */ {
 public:
  inline SC_START_FIELD_LOADING() : SC_START_FIELD_LOADING(nullptr) {}
  ~SC_START_FIELD_LOADING() override;
  explicit PROTOBUF_CONSTEXPR SC_START_FIELD_LOADING(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SC_START_FIELD_LOADING(const SC_START_FIELD_LOADING& from);
  SC_START_FIELD_LOADING(SC_START_FIELD_LOADING&& from) noexcept
    : SC_START_FIELD_LOADING() {
    *this = ::std::move(from);
  }

  inline SC_START_FIELD_LOADING& operator=(const SC_START_FIELD_LOADING& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_START_FIELD_LOADING& operator=(SC_START_FIELD_LOADING&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_START_FIELD_LOADING& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_START_FIELD_LOADING* internal_default_instance() {
    return reinterpret_cast<const SC_START_FIELD_LOADING*>(
               &_SC_START_FIELD_LOADING_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(SC_START_FIELD_LOADING& a, SC_START_FIELD_LOADING& b) {
    a.Swap(&b);
  }
  inline void Swap(SC_START_FIELD_LOADING* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_START_FIELD_LOADING* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_START_FIELD_LOADING* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SC_START_FIELD_LOADING>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SC_START_FIELD_LOADING& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SC_START_FIELD_LOADING& from) {
    SC_START_FIELD_LOADING::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SC_START_FIELD_LOADING* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.SC_START_FIELD_LOADING";
  }
  protected:
  explicit SC_START_FIELD_LOADING(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTargetMapIdFieldNumber = 1,
  };
  // uint32 target_map_id = 1;
  void clear_target_map_id();
  uint32_t target_map_id() const;
  void set_target_map_id(uint32_t value);
  private:
  uint32_t _internal_target_map_id() const;
  void _internal_set_target_map_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.SC_START_FIELD_LOADING)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t target_map_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class CS_FIELD_LOADING_COMPLETE final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.CS_FIELD_LOADING_COMPLETE) */ {
 public:
  inline CS_FIELD_LOADING_COMPLETE() : CS_FIELD_LOADING_COMPLETE(nullptr) {}
  ~CS_FIELD_LOADING_COMPLETE() override;
  explicit PROTOBUF_CONSTEXPR CS_FIELD_LOADING_COMPLETE(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CS_FIELD_LOADING_COMPLETE(const CS_FIELD_LOADING_COMPLETE& from);
  CS_FIELD_LOADING_COMPLETE(CS_FIELD_LOADING_COMPLETE&& from) noexcept
    : CS_FIELD_LOADING_COMPLETE() {
    *this = ::std::move(from);
  }

  inline CS_FIELD_LOADING_COMPLETE& operator=(const CS_FIELD_LOADING_COMPLETE& from) {
    CopyFrom(from);
    return *this;
  }
  inline CS_FIELD_LOADING_COMPLETE& operator=(CS_FIELD_LOADING_COMPLETE&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CS_FIELD_LOADING_COMPLETE& default_instance() {
    return *internal_default_instance();
  }
  static inline const CS_FIELD_LOADING_COMPLETE* internal_default_instance() {
    return reinterpret_cast<const CS_FIELD_LOADING_COMPLETE*>(
               &_CS_FIELD_LOADING_COMPLETE_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(CS_FIELD_LOADING_COMPLETE& a, CS_FIELD_LOADING_COMPLETE& b) {
    a.Swap(&b);
  }
  inline void Swap(CS_FIELD_LOADING_COMPLETE* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CS_FIELD_LOADING_COMPLETE* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CS_FIELD_LOADING_COMPLETE* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CS_FIELD_LOADING_COMPLETE>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CS_FIELD_LOADING_COMPLETE& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CS_FIELD_LOADING_COMPLETE& from) {
    CS_FIELD_LOADING_COMPLETE::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CS_FIELD_LOADING_COMPLETE* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.CS_FIELD_LOADING_COMPLETE";
  }
  protected:
  explicit CS_FIELD_LOADING_COMPLETE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIsSuccessFieldNumber = 1,
  };
  // bool is_success = 1;
  void clear_is_success();
  bool is_success() const;
  void set_is_success(bool value);
  private:
  bool _internal_is_success() const;
  void _internal_set_is_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.CS_FIELD_LOADING_COMPLETE)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool is_success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class SC_ENTER_FIELD final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.SC_ENTER_FIELD) */ {
 public:
  inline SC_ENTER_FIELD() : SC_ENTER_FIELD(nullptr) {}
  ~SC_ENTER_FIELD() override;
  explicit PROTOBUF_CONSTEXPR SC_ENTER_FIELD(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SC_ENTER_FIELD(const SC_ENTER_FIELD& from);
  SC_ENTER_FIELD(SC_ENTER_FIELD&& from) noexcept
    : SC_ENTER_FIELD() {
    *this = ::std::move(from);
  }

  inline SC_ENTER_FIELD& operator=(const SC_ENTER_FIELD& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_ENTER_FIELD& operator=(SC_ENTER_FIELD&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_ENTER_FIELD& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_ENTER_FIELD* internal_default_instance() {
    return reinterpret_cast<const SC_ENTER_FIELD*>(
               &_SC_ENTER_FIELD_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(SC_ENTER_FIELD& a, SC_ENTER_FIELD& b) {
    a.Swap(&b);
  }
  inline void Swap(SC_ENTER_FIELD* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_ENTER_FIELD* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_ENTER_FIELD* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SC_ENTER_FIELD>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SC_ENTER_FIELD& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SC_ENTER_FIELD& from) {
    SC_ENTER_FIELD::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SC_ENTER_FIELD* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.SC_ENTER_FIELD";
  }
  protected:
  explicit SC_ENTER_FIELD(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMyInfoFieldNumber = 1,
  };
  // .Protocol.PlayerInfo my_info = 1;
  bool has_my_info() const;
  private:
  bool _internal_has_my_info() const;
  public:
  void clear_my_info();
  const ::Protocol::PlayerInfo& my_info() const;
  PROTOBUF_NODISCARD ::Protocol::PlayerInfo* release_my_info();
  ::Protocol::PlayerInfo* mutable_my_info();
  void set_allocated_my_info(::Protocol::PlayerInfo* my_info);
  private:
  const ::Protocol::PlayerInfo& _internal_my_info() const;
  ::Protocol::PlayerInfo* _internal_mutable_my_info();
  public:
  void unsafe_arena_set_allocated_my_info(
      ::Protocol::PlayerInfo* my_info);
  ::Protocol::PlayerInfo* unsafe_arena_release_my_info();

  // @@protoc_insertion_point(class_scope:Protocol.SC_ENTER_FIELD)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::PlayerInfo* my_info_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class SC_SPAWN_PLAYER final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.SC_SPAWN_PLAYER) */ {
 public:
  inline SC_SPAWN_PLAYER() : SC_SPAWN_PLAYER(nullptr) {}
  ~SC_SPAWN_PLAYER() override;
  explicit PROTOBUF_CONSTEXPR SC_SPAWN_PLAYER(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SC_SPAWN_PLAYER(const SC_SPAWN_PLAYER& from);
  SC_SPAWN_PLAYER(SC_SPAWN_PLAYER&& from) noexcept
    : SC_SPAWN_PLAYER() {
    *this = ::std::move(from);
  }

  inline SC_SPAWN_PLAYER& operator=(const SC_SPAWN_PLAYER& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_SPAWN_PLAYER& operator=(SC_SPAWN_PLAYER&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_SPAWN_PLAYER& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_SPAWN_PLAYER* internal_default_instance() {
    return reinterpret_cast<const SC_SPAWN_PLAYER*>(
               &_SC_SPAWN_PLAYER_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(SC_SPAWN_PLAYER& a, SC_SPAWN_PLAYER& b) {
    a.Swap(&b);
  }
  inline void Swap(SC_SPAWN_PLAYER* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_SPAWN_PLAYER* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_SPAWN_PLAYER* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SC_SPAWN_PLAYER>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SC_SPAWN_PLAYER& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SC_SPAWN_PLAYER& from) {
    SC_SPAWN_PLAYER::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SC_SPAWN_PLAYER* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.SC_SPAWN_PLAYER";
  }
  protected:
  explicit SC_SPAWN_PLAYER(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInfoFieldNumber = 1,
  };
  // repeated .Protocol.PlayerInfo info = 1;
  int info_size() const;
  private:
  int _internal_info_size() const;
  public:
  void clear_info();
  ::Protocol::PlayerInfo* mutable_info(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::PlayerInfo >*
      mutable_info();
  private:
  const ::Protocol::PlayerInfo& _internal_info(int index) const;
  ::Protocol::PlayerInfo* _internal_add_info();
  public:
  const ::Protocol::PlayerInfo& info(int index) const;
  ::Protocol::PlayerInfo* add_info();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::PlayerInfo >&
      info() const;

  // @@protoc_insertion_point(class_scope:Protocol.SC_SPAWN_PLAYER)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::PlayerInfo > info_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class SC_DESPAWN_PLAYER final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.SC_DESPAWN_PLAYER) */ {
 public:
  inline SC_DESPAWN_PLAYER() : SC_DESPAWN_PLAYER(nullptr) {}
  ~SC_DESPAWN_PLAYER() override;
  explicit PROTOBUF_CONSTEXPR SC_DESPAWN_PLAYER(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SC_DESPAWN_PLAYER(const SC_DESPAWN_PLAYER& from);
  SC_DESPAWN_PLAYER(SC_DESPAWN_PLAYER&& from) noexcept
    : SC_DESPAWN_PLAYER() {
    *this = ::std::move(from);
  }

  inline SC_DESPAWN_PLAYER& operator=(const SC_DESPAWN_PLAYER& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_DESPAWN_PLAYER& operator=(SC_DESPAWN_PLAYER&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_DESPAWN_PLAYER& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_DESPAWN_PLAYER* internal_default_instance() {
    return reinterpret_cast<const SC_DESPAWN_PLAYER*>(
               &_SC_DESPAWN_PLAYER_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(SC_DESPAWN_PLAYER& a, SC_DESPAWN_PLAYER& b) {
    a.Swap(&b);
  }
  inline void Swap(SC_DESPAWN_PLAYER* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_DESPAWN_PLAYER* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_DESPAWN_PLAYER* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SC_DESPAWN_PLAYER>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SC_DESPAWN_PLAYER& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SC_DESPAWN_PLAYER& from) {
    SC_DESPAWN_PLAYER::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SC_DESPAWN_PLAYER* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.SC_DESPAWN_PLAYER";
  }
  protected:
  explicit SC_DESPAWN_PLAYER(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 1,
  };
  // uint64 player_id = 1;
  void clear_player_id();
  uint64_t player_id() const;
  void set_player_id(uint64_t value);
  private:
  uint64_t _internal_player_id() const;
  void _internal_set_player_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.SC_DESPAWN_PLAYER)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t player_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class CS_REQUEST_MOVE final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.CS_REQUEST_MOVE) */ {
 public:
  inline CS_REQUEST_MOVE() : CS_REQUEST_MOVE(nullptr) {}
  ~CS_REQUEST_MOVE() override;
  explicit PROTOBUF_CONSTEXPR CS_REQUEST_MOVE(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CS_REQUEST_MOVE(const CS_REQUEST_MOVE& from);
  CS_REQUEST_MOVE(CS_REQUEST_MOVE&& from) noexcept
    : CS_REQUEST_MOVE() {
    *this = ::std::move(from);
  }

  inline CS_REQUEST_MOVE& operator=(const CS_REQUEST_MOVE& from) {
    CopyFrom(from);
    return *this;
  }
  inline CS_REQUEST_MOVE& operator=(CS_REQUEST_MOVE&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CS_REQUEST_MOVE& default_instance() {
    return *internal_default_instance();
  }
  static inline const CS_REQUEST_MOVE* internal_default_instance() {
    return reinterpret_cast<const CS_REQUEST_MOVE*>(
               &_CS_REQUEST_MOVE_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(CS_REQUEST_MOVE& a, CS_REQUEST_MOVE& b) {
    a.Swap(&b);
  }
  inline void Swap(CS_REQUEST_MOVE* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CS_REQUEST_MOVE* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CS_REQUEST_MOVE* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CS_REQUEST_MOVE>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CS_REQUEST_MOVE& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CS_REQUEST_MOVE& from) {
    CS_REQUEST_MOVE::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CS_REQUEST_MOVE* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.CS_REQUEST_MOVE";
  }
  protected:
  explicit CS_REQUEST_MOVE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPosFieldNumber = 1,
  };
  // .Protocol.Vector3 pos = 1;
  bool has_pos() const;
  private:
  bool _internal_has_pos() const;
  public:
  void clear_pos();
  const ::Protocol::Vector3& pos() const;
  PROTOBUF_NODISCARD ::Protocol::Vector3* release_pos();
  ::Protocol::Vector3* mutable_pos();
  void set_allocated_pos(::Protocol::Vector3* pos);
  private:
  const ::Protocol::Vector3& _internal_pos() const;
  ::Protocol::Vector3* _internal_mutable_pos();
  public:
  void unsafe_arena_set_allocated_pos(
      ::Protocol::Vector3* pos);
  ::Protocol::Vector3* unsafe_arena_release_pos();

  // @@protoc_insertion_point(class_scope:Protocol.CS_REQUEST_MOVE)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::Vector3* pos_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class SC_MOVE_PATH final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.SC_MOVE_PATH) */ {
 public:
  inline SC_MOVE_PATH() : SC_MOVE_PATH(nullptr) {}
  ~SC_MOVE_PATH() override;
  explicit PROTOBUF_CONSTEXPR SC_MOVE_PATH(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SC_MOVE_PATH(const SC_MOVE_PATH& from);
  SC_MOVE_PATH(SC_MOVE_PATH&& from) noexcept
    : SC_MOVE_PATH() {
    *this = ::std::move(from);
  }

  inline SC_MOVE_PATH& operator=(const SC_MOVE_PATH& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_MOVE_PATH& operator=(SC_MOVE_PATH&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_MOVE_PATH& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_MOVE_PATH* internal_default_instance() {
    return reinterpret_cast<const SC_MOVE_PATH*>(
               &_SC_MOVE_PATH_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(SC_MOVE_PATH& a, SC_MOVE_PATH& b) {
    a.Swap(&b);
  }
  inline void Swap(SC_MOVE_PATH* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_MOVE_PATH* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_MOVE_PATH* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SC_MOVE_PATH>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SC_MOVE_PATH& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SC_MOVE_PATH& from) {
    SC_MOVE_PATH::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SC_MOVE_PATH* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.SC_MOVE_PATH";
  }
  protected:
  explicit SC_MOVE_PATH(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWaypointsFieldNumber = 3,
    kObjectIdFieldNumber = 1,
    kStartServerTickFieldNumber = 2,
  };
  // repeated .Protocol.Vector3 waypoints = 3;
  int waypoints_size() const;
  private:
  int _internal_waypoints_size() const;
  public:
  void clear_waypoints();
  ::Protocol::Vector3* mutable_waypoints(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Vector3 >*
      mutable_waypoints();
  private:
  const ::Protocol::Vector3& _internal_waypoints(int index) const;
  ::Protocol::Vector3* _internal_add_waypoints();
  public:
  const ::Protocol::Vector3& waypoints(int index) const;
  ::Protocol::Vector3* add_waypoints();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Vector3 >&
      waypoints() const;

  // uint64 object_id = 1;
  void clear_object_id();
  uint64_t object_id() const;
  void set_object_id(uint64_t value);
  private:
  uint64_t _internal_object_id() const;
  void _internal_set_object_id(uint64_t value);
  public:

  // uint64 start_server_tick = 2;
  void clear_start_server_tick();
  uint64_t start_server_tick() const;
  void set_start_server_tick(uint64_t value);
  private:
  uint64_t _internal_start_server_tick() const;
  void _internal_set_start_server_tick(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.SC_MOVE_PATH)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Vector3 > waypoints_;
    uint64_t object_id_;
    uint64_t start_server_tick_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class CS_TIME_SYNC final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.CS_TIME_SYNC) */ {
 public:
  inline CS_TIME_SYNC() : CS_TIME_SYNC(nullptr) {}
  ~CS_TIME_SYNC() override;
  explicit PROTOBUF_CONSTEXPR CS_TIME_SYNC(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CS_TIME_SYNC(const CS_TIME_SYNC& from);
  CS_TIME_SYNC(CS_TIME_SYNC&& from) noexcept
    : CS_TIME_SYNC() {
    *this = ::std::move(from);
  }

  inline CS_TIME_SYNC& operator=(const CS_TIME_SYNC& from) {
    CopyFrom(from);
    return *this;
  }
  inline CS_TIME_SYNC& operator=(CS_TIME_SYNC&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CS_TIME_SYNC& default_instance() {
    return *internal_default_instance();
  }
  static inline const CS_TIME_SYNC* internal_default_instance() {
    return reinterpret_cast<const CS_TIME_SYNC*>(
               &_CS_TIME_SYNC_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    11;

  friend void swap(CS_TIME_SYNC& a, CS_TIME_SYNC& b) {
    a.Swap(&b);
  }
  inline void Swap(CS_TIME_SYNC* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CS_TIME_SYNC* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CS_TIME_SYNC* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CS_TIME_SYNC>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CS_TIME_SYNC& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CS_TIME_SYNC& from) {
    CS_TIME_SYNC::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CS_TIME_SYNC* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.CS_TIME_SYNC";
  }
  protected:
  explicit CS_TIME_SYNC(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientTickFieldNumber = 1,
  };
  // uint64 client_tick = 1;
  void clear_client_tick();
  uint64_t client_tick() const;
  void set_client_tick(uint64_t value);
  private:
  uint64_t _internal_client_tick() const;
  void _internal_set_client_tick(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.CS_TIME_SYNC)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t client_tick_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class SC_TIME_SYNC final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.SC_TIME_SYNC) */ {
 public:
  inline SC_TIME_SYNC() : SC_TIME_SYNC(nullptr) {}
  ~SC_TIME_SYNC() override;
  explicit PROTOBUF_CONSTEXPR SC_TIME_SYNC(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SC_TIME_SYNC(const SC_TIME_SYNC& from);
  SC_TIME_SYNC(SC_TIME_SYNC&& from) noexcept
    : SC_TIME_SYNC() {
    *this = ::std::move(from);
  }

  inline SC_TIME_SYNC& operator=(const SC_TIME_SYNC& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_TIME_SYNC& operator=(SC_TIME_SYNC&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_TIME_SYNC& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_TIME_SYNC* internal_default_instance() {
    return reinterpret_cast<const SC_TIME_SYNC*>(
               &_SC_TIME_SYNC_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    12;

  friend void swap(SC_TIME_SYNC& a, SC_TIME_SYNC& b) {
    a.Swap(&b);
  }
  inline void Swap(SC_TIME_SYNC* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_TIME_SYNC* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_TIME_SYNC* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SC_TIME_SYNC>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SC_TIME_SYNC& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SC_TIME_SYNC& from) {
    SC_TIME_SYNC::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SC_TIME_SYNC* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.SC_TIME_SYNC";
  }
  protected:
  explicit SC_TIME_SYNC(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientTickFieldNumber = 1,
    kServerTickFieldNumber = 2,
  };
  // uint64 client_tick = 1;
  void clear_client_tick();
  uint64_t client_tick() const;
  void set_client_tick(uint64_t value);
  private:
  uint64_t _internal_client_tick() const;
  void _internal_set_client_tick(uint64_t value);
  public:

  // uint64 server_tick = 2;
  void clear_server_tick();
  uint64_t server_tick() const;
  void set_server_tick(uint64_t value);
  private:
  uint64_t _internal_server_tick() const;
  void _internal_set_server_tick(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.SC_TIME_SYNC)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t client_tick_;
    uint64_t server_tick_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CS_REQ_ENTER_GAME

// int32 char_id = 1;
inline void CS_REQ_ENTER_GAME::clear_char_id() {
  _impl_.char_id_ = 0;
}
inline int32_t CS_REQ_ENTER_GAME::_internal_char_id() const {
  return _impl_.char_id_;
}
inline int32_t CS_REQ_ENTER_GAME::char_id() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_REQ_ENTER_GAME.char_id)
  return _internal_char_id();
}
inline void CS_REQ_ENTER_GAME::_internal_set_char_id(int32_t value) {
  
  _impl_.char_id_ = value;
}
inline void CS_REQ_ENTER_GAME::set_char_id(int32_t value) {
  _internal_set_char_id(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_REQ_ENTER_GAME.char_id)
}

// int32 token = 2;
inline void CS_REQ_ENTER_GAME::clear_token() {
  _impl_.token_ = 0;
}
inline int32_t CS_REQ_ENTER_GAME::_internal_token() const {
  return _impl_.token_;
}
inline int32_t CS_REQ_ENTER_GAME::token() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_REQ_ENTER_GAME.token)
  return _internal_token();
}
inline void CS_REQ_ENTER_GAME::_internal_set_token(int32_t value) {
  
  _impl_.token_ = value;
}
inline void CS_REQ_ENTER_GAME::set_token(int32_t value) {
  _internal_set_token(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_REQ_ENTER_GAME.token)
}

// -------------------------------------------------------------------

// SC_ENTER_GAME_RESULT

// bool success = 1;
inline void SC_ENTER_GAME_RESULT::clear_success() {
  _impl_.success_ = false;
}
inline bool SC_ENTER_GAME_RESULT::_internal_success() const {
  return _impl_.success_;
}
inline bool SC_ENTER_GAME_RESULT::success() const {
  // @@protoc_insertion_point(field_get:Protocol.SC_ENTER_GAME_RESULT.success)
  return _internal_success();
}
inline void SC_ENTER_GAME_RESULT::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void SC_ENTER_GAME_RESULT::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.SC_ENTER_GAME_RESULT.success)
}

// int32 error_code = 2;
inline void SC_ENTER_GAME_RESULT::clear_error_code() {
  _impl_.error_code_ = 0;
}
inline int32_t SC_ENTER_GAME_RESULT::_internal_error_code() const {
  return _impl_.error_code_;
}
inline int32_t SC_ENTER_GAME_RESULT::error_code() const {
  // @@protoc_insertion_point(field_get:Protocol.SC_ENTER_GAME_RESULT.error_code)
  return _internal_error_code();
}
inline void SC_ENTER_GAME_RESULT::_internal_set_error_code(int32_t value) {
  
  _impl_.error_code_ = value;
}
inline void SC_ENTER_GAME_RESULT::set_error_code(int32_t value) {
  _internal_set_error_code(value);
  // @@protoc_insertion_point(field_set:Protocol.SC_ENTER_GAME_RESULT.error_code)
}

// -------------------------------------------------------------------

// CS_REQ_MOVE_FIELD

// uint32 map_id = 1;
inline void CS_REQ_MOVE_FIELD::clear_map_id() {
  _impl_.map_id_ = 0u;
}
inline uint32_t CS_REQ_MOVE_FIELD::_internal_map_id() const {
  return _impl_.map_id_;
}
inline uint32_t CS_REQ_MOVE_FIELD::map_id() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_REQ_MOVE_FIELD.map_id)
  return _internal_map_id();
}
inline void CS_REQ_MOVE_FIELD::_internal_set_map_id(uint32_t value) {
  
  _impl_.map_id_ = value;
}
inline void CS_REQ_MOVE_FIELD::set_map_id(uint32_t value) {
  _internal_set_map_id(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_REQ_MOVE_FIELD.map_id)
}

// -------------------------------------------------------------------

// SC_MOVE_FIELD_FAIL

// int32 error_code = 1;
inline void SC_MOVE_FIELD_FAIL::clear_error_code() {
  _impl_.error_code_ = 0;
}
inline int32_t SC_MOVE_FIELD_FAIL::_internal_error_code() const {
  return _impl_.error_code_;
}
inline int32_t SC_MOVE_FIELD_FAIL::error_code() const {
  // @@protoc_insertion_point(field_get:Protocol.SC_MOVE_FIELD_FAIL.error_code)
  return _internal_error_code();
}
inline void SC_MOVE_FIELD_FAIL::_internal_set_error_code(int32_t value) {
  
  _impl_.error_code_ = value;
}
inline void SC_MOVE_FIELD_FAIL::set_error_code(int32_t value) {
  _internal_set_error_code(value);
  // @@protoc_insertion_point(field_set:Protocol.SC_MOVE_FIELD_FAIL.error_code)
}

// -------------------------------------------------------------------

// SC_START_FIELD_LOADING

// uint32 target_map_id = 1;
inline void SC_START_FIELD_LOADING::clear_target_map_id() {
  _impl_.target_map_id_ = 0u;
}
inline uint32_t SC_START_FIELD_LOADING::_internal_target_map_id() const {
  return _impl_.target_map_id_;
}
inline uint32_t SC_START_FIELD_LOADING::target_map_id() const {
  // @@protoc_insertion_point(field_get:Protocol.SC_START_FIELD_LOADING.target_map_id)
  return _internal_target_map_id();
}
inline void SC_START_FIELD_LOADING::_internal_set_target_map_id(uint32_t value) {
  
  _impl_.target_map_id_ = value;
}
inline void SC_START_FIELD_LOADING::set_target_map_id(uint32_t value) {
  _internal_set_target_map_id(value);
  // @@protoc_insertion_point(field_set:Protocol.SC_START_FIELD_LOADING.target_map_id)
}

// -------------------------------------------------------------------

// CS_FIELD_LOADING_COMPLETE

// bool is_success = 1;
inline void CS_FIELD_LOADING_COMPLETE::clear_is_success() {
  _impl_.is_success_ = false;
}
inline bool CS_FIELD_LOADING_COMPLETE::_internal_is_success() const {
  return _impl_.is_success_;
}
inline bool CS_FIELD_LOADING_COMPLETE::is_success() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_FIELD_LOADING_COMPLETE.is_success)
  return _internal_is_success();
}
inline void CS_FIELD_LOADING_COMPLETE::_internal_set_is_success(bool value) {
  
  _impl_.is_success_ = value;
}
inline void CS_FIELD_LOADING_COMPLETE::set_is_success(bool value) {
  _internal_set_is_success(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_FIELD_LOADING_COMPLETE.is_success)
}

// -------------------------------------------------------------------

// SC_ENTER_FIELD

// .Protocol.PlayerInfo my_info = 1;
inline bool SC_ENTER_FIELD::_internal_has_my_info() const {
  return this != internal_default_instance() && _impl_.my_info_ != nullptr;
}
inline bool SC_ENTER_FIELD::has_my_info() const {
  return _internal_has_my_info();
}
inline const ::Protocol::PlayerInfo& SC_ENTER_FIELD::_internal_my_info() const {
  const ::Protocol::PlayerInfo* p = _impl_.my_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::PlayerInfo&>(
      ::Protocol::_PlayerInfo_default_instance_);
}
inline const ::Protocol::PlayerInfo& SC_ENTER_FIELD::my_info() const {
  // @@protoc_insertion_point(field_get:Protocol.SC_ENTER_FIELD.my_info)
  return _internal_my_info();
}
inline void SC_ENTER_FIELD::unsafe_arena_set_allocated_my_info(
    ::Protocol::PlayerInfo* my_info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.my_info_);
  }
  _impl_.my_info_ = my_info;
  if (my_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.SC_ENTER_FIELD.my_info)
}
inline ::Protocol::PlayerInfo* SC_ENTER_FIELD::release_my_info() {
  
  ::Protocol::PlayerInfo* temp = _impl_.my_info_;
  _impl_.my_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::PlayerInfo* SC_ENTER_FIELD::unsafe_arena_release_my_info() {
  // @@protoc_insertion_point(field_release:Protocol.SC_ENTER_FIELD.my_info)
  
  ::Protocol::PlayerInfo* temp = _impl_.my_info_;
  _impl_.my_info_ = nullptr;
  return temp;
}
inline ::Protocol::PlayerInfo* SC_ENTER_FIELD::_internal_mutable_my_info() {
  
  if (_impl_.my_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::PlayerInfo>(GetArenaForAllocation());
    _impl_.my_info_ = p;
  }
  return _impl_.my_info_;
}
inline ::Protocol::PlayerInfo* SC_ENTER_FIELD::mutable_my_info() {
  ::Protocol::PlayerInfo* _msg = _internal_mutable_my_info();
  // @@protoc_insertion_point(field_mutable:Protocol.SC_ENTER_FIELD.my_info)
  return _msg;
}
inline void SC_ENTER_FIELD::set_allocated_my_info(::Protocol::PlayerInfo* my_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.my_info_);
  }
  if (my_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(my_info));
    if (message_arena != submessage_arena) {
      my_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, my_info, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.my_info_ = my_info;
  // @@protoc_insertion_point(field_set_allocated:Protocol.SC_ENTER_FIELD.my_info)
}

// -------------------------------------------------------------------

// SC_SPAWN_PLAYER

// repeated .Protocol.PlayerInfo info = 1;
inline int SC_SPAWN_PLAYER::_internal_info_size() const {
  return _impl_.info_.size();
}
inline int SC_SPAWN_PLAYER::info_size() const {
  return _internal_info_size();
}
inline ::Protocol::PlayerInfo* SC_SPAWN_PLAYER::mutable_info(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.SC_SPAWN_PLAYER.info)
  return _impl_.info_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::PlayerInfo >*
SC_SPAWN_PLAYER::mutable_info() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.SC_SPAWN_PLAYER.info)
  return &_impl_.info_;
}
inline const ::Protocol::PlayerInfo& SC_SPAWN_PLAYER::_internal_info(int index) const {
  return _impl_.info_.Get(index);
}
inline const ::Protocol::PlayerInfo& SC_SPAWN_PLAYER::info(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.SC_SPAWN_PLAYER.info)
  return _internal_info(index);
}
inline ::Protocol::PlayerInfo* SC_SPAWN_PLAYER::_internal_add_info() {
  return _impl_.info_.Add();
}
inline ::Protocol::PlayerInfo* SC_SPAWN_PLAYER::add_info() {
  ::Protocol::PlayerInfo* _add = _internal_add_info();
  // @@protoc_insertion_point(field_add:Protocol.SC_SPAWN_PLAYER.info)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::PlayerInfo >&
SC_SPAWN_PLAYER::info() const {
  // @@protoc_insertion_point(field_list:Protocol.SC_SPAWN_PLAYER.info)
  return _impl_.info_;
}

// -------------------------------------------------------------------

// SC_DESPAWN_PLAYER

// uint64 player_id = 1;
inline void SC_DESPAWN_PLAYER::clear_player_id() {
  _impl_.player_id_ = uint64_t{0u};
}
inline uint64_t SC_DESPAWN_PLAYER::_internal_player_id() const {
  return _impl_.player_id_;
}
inline uint64_t SC_DESPAWN_PLAYER::player_id() const {
  // @@protoc_insertion_point(field_get:Protocol.SC_DESPAWN_PLAYER.player_id)
  return _internal_player_id();
}
inline void SC_DESPAWN_PLAYER::_internal_set_player_id(uint64_t value) {
  
  _impl_.player_id_ = value;
}
inline void SC_DESPAWN_PLAYER::set_player_id(uint64_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:Protocol.SC_DESPAWN_PLAYER.player_id)
}

// -------------------------------------------------------------------

// CS_REQUEST_MOVE

// .Protocol.Vector3 pos = 1;
inline bool CS_REQUEST_MOVE::_internal_has_pos() const {
  return this != internal_default_instance() && _impl_.pos_ != nullptr;
}
inline bool CS_REQUEST_MOVE::has_pos() const {
  return _internal_has_pos();
}
inline const ::Protocol::Vector3& CS_REQUEST_MOVE::_internal_pos() const {
  const ::Protocol::Vector3* p = _impl_.pos_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vector3&>(
      ::Protocol::_Vector3_default_instance_);
}
inline const ::Protocol::Vector3& CS_REQUEST_MOVE::pos() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_REQUEST_MOVE.pos)
  return _internal_pos();
}
inline void CS_REQUEST_MOVE::unsafe_arena_set_allocated_pos(
    ::Protocol::Vector3* pos) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pos_);
  }
  _impl_.pos_ = pos;
  if (pos) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.CS_REQUEST_MOVE.pos)
}
inline ::Protocol::Vector3* CS_REQUEST_MOVE::release_pos() {
  
  ::Protocol::Vector3* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Vector3* CS_REQUEST_MOVE::unsafe_arena_release_pos() {
  // @@protoc_insertion_point(field_release:Protocol.CS_REQUEST_MOVE.pos)
  
  ::Protocol::Vector3* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
  return temp;
}
inline ::Protocol::Vector3* CS_REQUEST_MOVE::_internal_mutable_pos() {
  
  if (_impl_.pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Vector3>(GetArenaForAllocation());
    _impl_.pos_ = p;
  }
  return _impl_.pos_;
}
inline ::Protocol::Vector3* CS_REQUEST_MOVE::mutable_pos() {
  ::Protocol::Vector3* _msg = _internal_mutable_pos();
  // @@protoc_insertion_point(field_mutable:Protocol.CS_REQUEST_MOVE.pos)
  return _msg;
}
inline void CS_REQUEST_MOVE::set_allocated_pos(::Protocol::Vector3* pos) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pos_);
  }
  if (pos) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pos));
    if (message_arena != submessage_arena) {
      pos = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pos, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.pos_ = pos;
  // @@protoc_insertion_point(field_set_allocated:Protocol.CS_REQUEST_MOVE.pos)
}

// -------------------------------------------------------------------

// SC_MOVE_PATH

// uint64 object_id = 1;
inline void SC_MOVE_PATH::clear_object_id() {
  _impl_.object_id_ = uint64_t{0u};
}
inline uint64_t SC_MOVE_PATH::_internal_object_id() const {
  return _impl_.object_id_;
}
inline uint64_t SC_MOVE_PATH::object_id() const {
  // @@protoc_insertion_point(field_get:Protocol.SC_MOVE_PATH.object_id)
  return _internal_object_id();
}
inline void SC_MOVE_PATH::_internal_set_object_id(uint64_t value) {
  
  _impl_.object_id_ = value;
}
inline void SC_MOVE_PATH::set_object_id(uint64_t value) {
  _internal_set_object_id(value);
  // @@protoc_insertion_point(field_set:Protocol.SC_MOVE_PATH.object_id)
}

// uint64 start_server_tick = 2;
inline void SC_MOVE_PATH::clear_start_server_tick() {
  _impl_.start_server_tick_ = uint64_t{0u};
}
inline uint64_t SC_MOVE_PATH::_internal_start_server_tick() const {
  return _impl_.start_server_tick_;
}
inline uint64_t SC_MOVE_PATH::start_server_tick() const {
  // @@protoc_insertion_point(field_get:Protocol.SC_MOVE_PATH.start_server_tick)
  return _internal_start_server_tick();
}
inline void SC_MOVE_PATH::_internal_set_start_server_tick(uint64_t value) {
  
  _impl_.start_server_tick_ = value;
}
inline void SC_MOVE_PATH::set_start_server_tick(uint64_t value) {
  _internal_set_start_server_tick(value);
  // @@protoc_insertion_point(field_set:Protocol.SC_MOVE_PATH.start_server_tick)
}

// repeated .Protocol.Vector3 waypoints = 3;
inline int SC_MOVE_PATH::_internal_waypoints_size() const {
  return _impl_.waypoints_.size();
}
inline int SC_MOVE_PATH::waypoints_size() const {
  return _internal_waypoints_size();
}
inline ::Protocol::Vector3* SC_MOVE_PATH::mutable_waypoints(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.SC_MOVE_PATH.waypoints)
  return _impl_.waypoints_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Vector3 >*
SC_MOVE_PATH::mutable_waypoints() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.SC_MOVE_PATH.waypoints)
  return &_impl_.waypoints_;
}
inline const ::Protocol::Vector3& SC_MOVE_PATH::_internal_waypoints(int index) const {
  return _impl_.waypoints_.Get(index);
}
inline const ::Protocol::Vector3& SC_MOVE_PATH::waypoints(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.SC_MOVE_PATH.waypoints)
  return _internal_waypoints(index);
}
inline ::Protocol::Vector3* SC_MOVE_PATH::_internal_add_waypoints() {
  return _impl_.waypoints_.Add();
}
inline ::Protocol::Vector3* SC_MOVE_PATH::add_waypoints() {
  ::Protocol::Vector3* _add = _internal_add_waypoints();
  // @@protoc_insertion_point(field_add:Protocol.SC_MOVE_PATH.waypoints)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Vector3 >&
SC_MOVE_PATH::waypoints() const {
  // @@protoc_insertion_point(field_list:Protocol.SC_MOVE_PATH.waypoints)
  return _impl_.waypoints_;
}

// -------------------------------------------------------------------

// CS_TIME_SYNC

// uint64 client_tick = 1;
inline void CS_TIME_SYNC::clear_client_tick() {
  _impl_.client_tick_ = uint64_t{0u};
}
inline uint64_t CS_TIME_SYNC::_internal_client_tick() const {
  return _impl_.client_tick_;
}
inline uint64_t CS_TIME_SYNC::client_tick() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_TIME_SYNC.client_tick)
  return _internal_client_tick();
}
inline void CS_TIME_SYNC::_internal_set_client_tick(uint64_t value) {
  
  _impl_.client_tick_ = value;
}
inline void CS_TIME_SYNC::set_client_tick(uint64_t value) {
  _internal_set_client_tick(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_TIME_SYNC.client_tick)
}

// -------------------------------------------------------------------

// SC_TIME_SYNC

// uint64 client_tick = 1;
inline void SC_TIME_SYNC::clear_client_tick() {
  _impl_.client_tick_ = uint64_t{0u};
}
inline uint64_t SC_TIME_SYNC::_internal_client_tick() const {
  return _impl_.client_tick_;
}
inline uint64_t SC_TIME_SYNC::client_tick() const {
  // @@protoc_insertion_point(field_get:Protocol.SC_TIME_SYNC.client_tick)
  return _internal_client_tick();
}
inline void SC_TIME_SYNC::_internal_set_client_tick(uint64_t value) {
  
  _impl_.client_tick_ = value;
}
inline void SC_TIME_SYNC::set_client_tick(uint64_t value) {
  _internal_set_client_tick(value);
  // @@protoc_insertion_point(field_set:Protocol.SC_TIME_SYNC.client_tick)
}

// uint64 server_tick = 2;
inline void SC_TIME_SYNC::clear_server_tick() {
  _impl_.server_tick_ = uint64_t{0u};
}
inline uint64_t SC_TIME_SYNC::_internal_server_tick() const {
  return _impl_.server_tick_;
}
inline uint64_t SC_TIME_SYNC::server_tick() const {
  // @@protoc_insertion_point(field_get:Protocol.SC_TIME_SYNC.server_tick)
  return _internal_server_tick();
}
inline void SC_TIME_SYNC::_internal_set_server_tick(uint64_t value) {
  
  _impl_.server_tick_ = value;
}
inline void SC_TIME_SYNC::set_server_tick(uint64_t value) {
  _internal_set_server_tick(value);
  // @@protoc_insertion_point(field_set:Protocol.SC_TIME_SYNC.server_tick)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
